# Generated by Django 2.2 on 2022-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('image_path', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Champagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('image_path', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, null=True)),
                ('text', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('image_path', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
    ]
