# Generated by Django 2.2 on 2022-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vodka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('image_path', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(default='', max_length=255, null=True)),
            ],
        ),
    ]
