# Generated by Django 2.2 on 2022-04-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vodka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'verbose_name': ('Beer',), 'verbose_name_plural': 'Beer'},
        ),
        migrations.AlterModelOptions(
            name='champagne',
            options={'verbose_name': ('Champagne',), 'verbose_name_plural': 'Champagne'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': ('Comment',), 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='vodka',
            options={'verbose_name': ('Vodka',), 'verbose_name_plural': 'Vodka'},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'verbose_name': ('Wine',), 'verbose_name_plural': 'Wine'},
        ),
    ]
